spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: docker

  jpa:
    generate-ddl: true
    show-sql: true

  output:
    ansi:
      enabled: always
